name: David Saunders Photography
favicon: null
layout_spectrum: 0.3554273231420666
typography_spectrum: 0.7913562282919884
title: David Saunders Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#acb0b9'
    - '#005182'
    - '#8590a3'
    - '#60748f'
    - '#000000'
  brandStrength: 0.46174541348591447
  lightness: 0.43042427697218955
  saturation: 0.19197182590141892
  rhythmicContrast: 0.002909426111727953
purpose: []
